nodeLinker: node-modules

npmAuthToken: "${NPM_AUTH_TOKEN:-}"

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: "https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
